#!/bin/sh
set -e

# custom script to overwrite stikked config variables
bash /bin/replace-envvars.sh

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php "$@"
fi

exec "$@"
