<?php
/**
 * Class and Function List:
 * Function list:
 * Classes list:
 */

if (!defined('BASEPATH')) exit('No direct script access allowed');

//codemirror languages
$config['ace_languages'] = array(
	'text' => 'text',
	'html5' => 'html',
	'css' => 'css',
	'javascript' => 'javascript',
	'php' => 'php',
	'python' => 'python',
	'ruby' => 'ruby',
	'lua' => 'lua',
	'bash' => 'sh',
	'erlang' => 'erlang',
	'go' => 'golang',
	'c' => 'c_cpp',
	'cpp' => 'c_cpp',
	'diff' => 'diff',
	'latex' => 'latex',
	'sql' => 'sql',
	'xml' => 'xml',
	'abap' => 'abap',
	'actionscript' => 'actionscript',
	'actionscript3' => 'actionscript',
	'ada' => 'ada',
	'apache' => 'apache_conf',
	'applescript' => 'applescript',
	'asm' => 'assembly_x86',
	'autohotkey' => 'autohotkey',
	'closure' => 'closure',
	'cobol' => 'cobol',
	'coffeescript' => 'coffee',
	'coffeescript' => 'coffee',
	'cpp-winapi' => 'c_cpp',
	'c_loadrunner' => 'c_cpp',
	'c_mac' => 'c_cpp',
	'c_winapi' => 'c_cpp',
	'csharp' => 'csharp',
	'css' => 'css',
	'd' => 'd',
	'dart' => 'dart',
	'dot' => 'dot',
	'eiffel' => 'eiffel',
	'fortran' => 'fortran',
	'groovy' => 'groovy',
	'haskell' => 'haskell',
	'haxe' => 'haxe',
	'ini' => 'ini',
	'io' => 'io',
	'java' => 'java',
	'java5' => 'java',
	'make' => 'makefile',
	'matlab' => 'matlab',
	'mysql' => 'mysql',
	'objc' => 'objectivec',
	'ocaml' => 'ocaml',
	'pascal' => 'pascal',
	'perl' => 'perl',
	'perl6' => 'perl',
	'postgresql' => 'pgsql',
	'powershell' => 'powershell',
	'prolog' => 'prolog',
	'properties' => 'properties',
	'rails' => 'ruby',
	'rust' => 'rust',
	'scala' => 'scala',
	'scheme' => 'scheme',
	'smarty' => 'smarty',
	'tcl' => 'tcl',
	'vala' => 'vala',
	'vb' => 'vbscript',
	'verilog' => 'verilog',
	'vhdl' => 'vhdl',
	'yaml' => 'yaml',
);
