<?php
/**
 * Class and Function List:
 * Function list:
 * Classes list:
 */

if (!defined('BASEPATH')) exit('No direct script access allowed');

//geshi languages
$config['geshi_languages'] = array(
	'c' => 'C',
	'css' => 'CSS',
	'cpp' => 'C++',
	'html4strict' => 'HTML (4 Strict)',
	'java' => 'Java',
	'perl' => 'Perl',
	'php' => 'PHP',
	'python' => 'Python',
	'ruby' => 'Ruby',
	'text' => 'Plain Text',
	'asm' => 'ASM (Nasm Syntax)',
	'xhtml' => 'XHTML',
	'actionscript' => 'Actionscript',
	'ada' => 'ADA',
	'apache' => 'Apache Log',
	'applescript' => 'AppleScript',
	'autoit' => 'AutoIT',
	'bash' => 'Bash',
	'bptzbasic' => 'BptzBasic',
	'c_mac' => 'C for Macs',
	'csharp' => 'C#',
	'ColdFusion' => 'coldfusion',
	'delphi' => 'Delphi',
	'eiffel' => 'Eiffel',
	'fortran' => 'Fortran',
	'freebasic' => 'FreeBasic',
	'gml' => 'GML',
	'groovy' => 'Groovy',
	'inno' => 'Inno',
	'java5' => 'Java 5',
	'javascript' => 'Javascript',
	'latex' => 'LaTeX',
	'mirc' => 'mIRC',
	'mysql' => 'MySQL',
	'nsis' => 'NSIS',
	'objc' => 'Objective C',
	'ocaml' => 'OCaml',
	'oobas' => 'OpenOffice BASIC',
	'orcale8' => 'Orcale 8 SQL',
	'pascal' => 'Pascal',
	'plsql' => 'PL/SQL',
	'qbasic' => 'Q(uick)BASIC',
	'robots' => 'robots.txt',
	'scheme' => 'Scheme',
	'sdlbasic' => 'SDLBasic',
	'smalltalk' => 'Smalltalk',
	'smarty' => 'Smarty',
	'sql' => 'SQL',
	'tcl' => 'TCL',
	'vbnet' => 'VB.NET',
	'vb' => 'Visual BASIC',
	'winbatch' => 'Winbatch',
	'xml' => 'XML',
	'z80' => 'z80 ASM',
);
