<?php
/**
 * Class and Function List:
 * Function list:
 * Classes list:
 */

if (!defined('BASEPATH')) exit('No direct script access allowed');

//geshi languages
$config['geshi_languages'] = array(
	'html4strict' => 'HTML',
	'css' => 'CSS',
	'javascript' => 'JavaScript',
	'php' => 'PHP',
	'python' => 'Python',
	'ruby' => 'Ruby',
	'bash' => 'Bash',
	'c' => 'C',
	'cpp' => 'C++',
	'diff' => 'Diff',
	'latex' => 'LaTeX',
	'sql' => 'SQL',
	'xml' => 'XML',
	'text' => 'Plain Text',
	'abap' => 'ABAP',
	'actionscript' => 'Actionscript',
	'ada' => 'ADA',
	'apache' => 'Apache Log',
	'applescript' => 'AppleScript',
	'asm' => 'Assembler',
	'asp' => 'ASP',
	'autoit' => 'AutoIt',
	'blitzbasic' => 'Blitzbasic',
	'bnf' => 'Backus-Naur-Form',
	'c_mac' => 'C for Macs',
	'caddcl' => 'CAD DCL',
	'cadlisp' => 'CAD Lisp',
	'cfdg' => 'CFDG',
	'cfm' => 'CFM',
	'cpp-qt' => 'C++ QT',
	'csharp' => 'C#',
	'd' => 'D',
	'delphi' => 'Delphi',
	'div' => 'DIV',
	'dos' => 'DOS',
	'dot' => 'dot',
	'eiffel' => 'Eiffel',
	'fortran' => 'Fortran',
	'freebasic' => 'FreeBasic',
	'genero' => 'Genero',
	'gml' => 'GML',
	'groovy' => 'Groovy',
	'haskell' => 'Haskell',
	'idl' => 'Unoidl',
	'ini' => 'INI',
	'inno' => 'Inno Script',
	'io' => 'Io',
	'java' => 'Java',
	'java5' => 'Java 5',
	'lisp' => 'Lisp',
	'lua' => 'LUA',
	'm68k' => 'm68k',
	'matlab' => 'Matlab',
	'mirc' => 'mIRC',
	'mpasm' => 'MPASM',
	'mysql' => 'MySQL',
	'nsis' => 'NSIS',
	'objc' => 'Objective C',
	'ocaml' => 'ocaml',
	'oobas' => 'OpenOffice.org Basic',
	'oracle8' => 'Orcale 8 SQL',
	'pascal' => 'Pascal',
	'per' => 'Per',
	'perl' => 'Perl',
	'plsql' => 'PL/SQL',
	'qbasic' => 'QBasic',
	'rails' => 'Rails',
	'reg' => 'Registry',
	'robots' => 'robots.txt',
	'sas' => 'SAS',
	'scheme' => 'Scheme',
	'sdlbasic' => 'sdlBasic',
	'smalltalk' => 'Smalltalk',
	'smarty' => 'Smarty',
	'tcl' => 'TCL',
	'thinbasic' => 'thinBasic',
	'tsql' => 'T-SQL',
	'vb' => 'Visual Basic',
	'vbnet' => 'VB.NET',
	'vhdl' => 'VHDL',
	'visualfoxpro' => 'Visual FoxPro',
	'winbatch' => 'WinBatch',
	'xpp' => 'X++',
	'z80' => 'Z80',
);
